server:
  port: 8088

spring:
  redis:
    host: 127.0.0.1
    database: 0
    password:
    username:
    jedis:
      pool:
        max-active: 64
        max-idle: 64
        min-idle: 2
        max-wait: 10ms
